### ISSUE TITLE
sprintf second parameter missing

### ISSUE THREAD

**Issue by rusnak** [kassko/data-mapper#39]
Missed the second parameter in the sprintf call.

Class: *\Kassko\DataMapper\ClassMetadata\SourcePropertyMetadata*
Method: *areDataInvalid*
Block:
```php
default:
    throw new DomainException(sprintf('The bad return value "%s" is not allowed.'));
```

**Comment by kassko** [comment]
It's fixed by the PR
https://github.com/kassko/data-mapper/pull/40

Thank you !
